export const MATH = {
    COMPUTING: "COMPUTING_OPERATIONS",
    COMPUTED_MUL: "COMPUTED_MUL",
    COMPUTED_DIV: "COMPUTED_DIV",
    COMPUTED_SQRT: "COMPUTED_SQRT",
    COMPUTED_ERROR: "COMPUTED_ERROR",
    COMPUTED_SUCCESS: "COMPUTED_SUCCESS",

}